inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Naming/MethodName:
  EnforcedStyle: snake_case
  Exclude:
    - 'test/tests.rb' # test_IO doesn't match

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
